# Generated by Django 3.2 on 2026-04-11 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HargaFasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.IntegerField(default=50000)),
                ('ac', models.IntegerField(default=0)),
                ('kipas_angin', models.IntegerField(default=0)),
                ('rice_cooker', models.IntegerField(default=0)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kamar', models.CharField(max_length=10)),
                ('harga', models.IntegerField()),
                ('status', models.CharField(choices=[('Kosong', 'Kosong'), ('Terisi', 'Terisi')], default='Kosong', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(choices=[('Listrik', 'Listrik'), ('Wifi', 'Wifi'), ('Air', 'Air'), ('Perawatan', 'Perawatan'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50)),
                ('keterangan', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Penyewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('nik', models.CharField(max_length=16)),
                ('tanggal_masuk', models.DateField()),
                ('tanggal_keluar', models.DateField(blank=True, null=True)),
                ('foto_ktp', models.ImageField(blank=True, null=True, upload_to='ktp/')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Keluar', 'Keluar')], default='Aktif', max_length=20)),
                ('fasilitas', models.ManyToManyField(blank=True, to='kos.Fasilitas')),
                ('kamar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kos.kamar')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tagihan', models.DateField(default=django.utils.timezone.now)),
                ('bulan', models.CharField(max_length=20)),
                ('tahun', models.IntegerField()),
                ('biaya_kamar', models.IntegerField()),
                ('listrik', models.IntegerField(default=50000)),
                ('air', models.IntegerField(default=30000)),
                ('wifi', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('leskuker', models.IntegerField(default=0)),
                ('kipas_angin', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('dibayar', models.IntegerField(default=0)),
                ('sisa', models.IntegerField(default=0)),
                ('status', models.CharField(default='Belum Bayar', max_length=20)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kos.penyewa')),
            ],
            options={
                'unique_together': {('penyewa', 'bulan', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateField(default=django.utils.timezone.now)),
                ('jumlah_bayar', models.IntegerField()),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kos.tagihan')),
            ],
        ),
    ]
