# Generated by Django 3.2 on 2026-04-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagihan',
            old_name='leskuker',
            new_name='rice_cooker',
        ),
    ]
