# Generated by Django 3.2 on 2026-04-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0002_rename_leskuker_tagihan_rice_cooker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyewa',
            name='kamar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kos.kamar'),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='nik',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='no_hp',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Aktif', 'Aktif'), ('Keluar', 'Keluar')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='tanggal_masuk',
            field=models.DateField(blank=True, null=True),
        ),
    ]
