# Generated by Django 3.2 on 2026-04-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0003_auto_20260413_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPindahKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_request', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pending', max_length=20)),
                ('kamar_tujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kos.kamar')),
                ('penyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kos.penyewa')),
            ],
        ),
    ]
