# Generated by Django 3.2 on 2026-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0004_requestpindahkamar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='bukti_bayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
    ]
