# Generated by Django 3.2 on 2026-07-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0005_pembayaran_bukti_bayar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagihan',
            name='biaya_pindah',
            field=models.IntegerField(default=0),
        ),
    ]
