# Generated by Django 3.2 on 2026-07-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0006_tagihan_biaya_pindah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpindahkamar',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak'), ('Selesai', 'Selesai')], default='Pending', max_length=20),
        ),
    ]
