# Generated by Django 3.2 on 2026-08-04 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kos', '0007_alter_requestpindahkamar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpindahkamar',
            name='kamar_asal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pindah_asal', to='kos.kamar'),
        ),
    ]
